version: "3.2"

services:
  files_management:
    restart: on-failure
    image: files_management
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/filesystem
      - DB_USER_NAME=postgres
      - DB_PASSWORD=admin
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=filesystem

